### ISSUE TITLE
CreateCommandsInvoker stuck in CREATE_IN_PROGRESS

### ISSUE THREAD

**Issue by EsteFilipe** [ytausch/serverless-discord-bot#19]
After running `sam build` and then `sam deploy --guided` my stack creation gets stuck in CREATE_IN_PROGRESS.

In the stack resources everything succeeds to create, except CreateCommandsInvoker, which is stuck. I have no idea how to debug this, any suggestions?

Edit:

Upon closer inspection figured that the lambda CreateCommands isn't finding the `slash-create` dependency but still haven't managed to solve it. Here's what I see in CloudWatch:

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'slash-create'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'slash-create'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Comment by EsteFilipe** [comment]
Alright, figured it out. You need to run "npm install" inside the layer's folder, otherwise the layer doesn't include the dependencies.

**Comment by ytausch** [comment]
Yep exactly, that was missing in the README. Sorry - I've fixed it. Thanks for reporting!
